//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Images = new HashSet<Image>();
            this.Messages = new HashSet<Message>();
            this.Seller_Approved_book = new HashSet<Seller_Approved_book>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Points { get; set; }
        public string Discription { get; set; }
        public System.DateTime Date_Uploaded { get; set; }
        public Nullable<int> Subcategory_Id { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> City_Id { get; set; }
    
        public virtual City City { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seller_Approved_book> Seller_Approved_book { get; set; }
    }
}
