//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Buyer_Id { get; set; }
        public int Seller_Id { get; set; }
        public int Book_Id { get; set; }
        public string User_Review { get; set; }
        public int Rate { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Seller_Buyer_Book Seller_Buyer_Book { get; set; }
    }
}
