//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller_Approved_book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seller_Approved_book()
        {
            this.Requests = new HashSet<Request>();
            this.Seller_Buyer_Book = new HashSet<Seller_Buyer_Book>();
        }
    
        public int Seller_Id { get; set; }
        public int Book_Id { get; set; }
        public string Approved { get; set; }
    
        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seller_Buyer_Book> Seller_Buyer_Book { get; set; }
    }
}
